// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

const findTheDifference = function(s, t) {
  const obj = {};
  for (let i = 0; i < s.length; i++) {
    obj[s[i]] ? obj[s[i]]++ : obj[s[i]] = 1;
  }
  for (let i = 0; i < t.length; i++) {
    if (obj[t[i]]) {
      if (obj[t[i]] === 1) {
        delete obj[t[i]];
      } else {
        obj[t[i]]--;
      }
    } else {
      return t[i];
    }
  }
  return Object.keys(obj)[0];
};

const testS = 'abcd';
const testT = 'abcda';

console.log(findTheDifference(testS, testT))